export const RECIFE_NEIGHBORHOODS = [
  "Boa Viagem",
  "Pina",
  "Brasília Teimosa",
  "Imbiribeira",
  "Ibura",
  "Torreão",
  "Ilha do Retiro",
  "Boa Vista",
  "Espinheiro",
  "Graças",
  "Casa Forte",
  "Parnamirim",
  "Poço da Panela",
  "Santo Amaro",
  "Derby",
  "Torre",
  "Madalena",
  "Ilha do Leite",
  "Recife (bairro)",
  "Santo Antônio",
  "São José",
  "Cordeiro",
  "Várzea",
  "Iputinga",
  "Caxangá",
  "Afogados",
  "Jaqueira",
  "Aflitos",
  "Tamarineira",
] as const;

export type RecifeNeighborhood = (typeof RECIFE_NEIGHBORHOODS)[number];
